pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
            }
        }
        stage('Install dependencies') {
                            steps {
                                sh 'composer install'
                                sh 'composer require --dev phpunit/phpunit'
                            }
                        }
        stage('Test') {
            steps {
                script {
                    echo 'Testing...'
                    sh '/var/www/html/vendor/bin/phpunit /var/www/html/tests'
                }
            }
        }
        stage('SonarQube') {
            steps {
                script { scannerHome = tool 'Sonar Scanner' }
                withSonarQubeEnv('SonarQube') {
                    sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=sonarqubetes1"
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}